### ISSUE TITLE
Request Feature

### ISSUE THREAD

**Issue by dayrlism10** [GabeEddyT/gatsby-image-background-slider#1]
Hi, was wondering if you can add on the feature for next or previous button trigger function.

**Comment by GabeEddyT** [comment]
Sure, could you elaborate/mark up what you have in mind?

**Comment by iandstevens92** [comment]
Hi, I was just wondering if anyone is busy with this or I could make a pr? I'm thinking dots saying what photo it's on can clicking on them to change it. e.g.  https://mavela.co.za/

**Comment by GabeEddyT** [comment]
Feel free to make a PR if you have an implementation I can test.

**Comment by GabeEddyT** [comment]
To address @dayrlism10's original issue, I added a prop (`callbacks`) to interface with the slider. Example usage for `prev` and `next` buttons:

```jsx
let setBg = {}; // define empty object outside of render function
// ...
return (
  <BackgroundSlider
  // ... other props ...
  callbacks = {setBg} // assign object to callbacks prop
  />
  // use callbacks
  <button onClick={ () => setBg.prev() }>prev</button>
  <button onClick={ () => setBg.next() }>next</button>
);
```

In addressing @iandstevens92's pagination suggestion, I made a simple component to illustrate the usage of `onChange` and `atIndex`: 
```jsx
import BackgroundSlider, {Pagination} from 'gatsby-image-background-slider`
```
But I encourage making your own with SVG icons, styling, animations, etc. instead of &middot; HTML entities ... Example usage of these dots in the upper-left of my own site: 
```jsx
<div style={{position: 'absolute', top: '1em', left: '1em'}}>
  <Pagination callbacks={setBg}/>
</div>
```
![image](https://user-images.githubusercontent.com/17380372/77638598-c8b8ff00-6f2d-11ea-9238-7908cc57566b.png)
